<?php
##########################################
# paBox v1.6
# Lead Programmer: Matt Humphrey (PHPAlien) >> matt@phparena.net <<
# Version 1.6
# 18 May 2002
# Copyright 2002 PHP Arena. All rights reserved.
#
# Swearfilter Module
# Module Written by Matt Humphrey
# Module Date: 27-02-2002
# Module Version: 1.0
##########################################

function stopswearing($text) {

$word = array(
				"\@\$\$" => "butt",
				"a\$\$" => "butt",
				"anton" => "[censored]",
				"arse" => "butt",
				"arsehole" => "[censored]",
				"ass" => "butt",
				"ass muncher" => "[censored]",
				"asshole" => "[censored]",
				"asstooling" => "[censored]",
				"asswipe" => "[censored]",
				"b\!tch" => "[censored]",
				"b17ch" => "[censored]",
				"b1tch" => "[censored]",
				"bastard" => "[censored]",
				"beefcurtins" => "[censored]",
				"bellend" => "[censored]",
				"bi7ch" => "[censored]",
				"bitch" => "[censored]",
				"bitchy" => "[censored]",
				"boiolas" => "[censored]",
				"bollocks" => "[censored]",
				"breasts" => "[censored]",
				"brown nose" => "[censored]",
				"bugger" => "damn",
				"butt pirate" => "[censored]",
				"c0ck" => "[censored]",
				"cawk" => "[censored]",
				"chink" => "[censored]",
				"clitsaq" => "[censored]",
				"cock" => "[censored]",
				"cockbite" => "[censored]",
				"cockgobbler" => "[censored]",
				"cocksucker" => "[censored]",
				"cum" => "[censored]",
				"cunt" => "[censored]",
				"dago" => "[censored]",
				"daygo" => "[censored]",
				"dego" => "[censored]",
				"dick" => "[censored]",
				"dick wad" => "[censored]",
				"dickhead" => "[censored]",
				"dickweed" => "[censored]",
				"douchebag" => "[censored]",
				"dziwka" => "[censored]",
				"ekto" => "[censored]",
				"enculer" => "[censored]",
				"faen" => "[censored]",
				"fag" => "[censored]",
				"faggot" => "[censored]",
				"fart" => "[censored]",
				"fatass" => "[censored]",
				"feg" => "[censored]",
				"felch" => "[censored]",
				"ficken" => "[censored]",
				"fitta" => "[censored]",
				"fitte" => "[censored]",
				"flikker" => "[censored]",
				"fok" => "$#%!",
				"fuck" => "$#%!",
				"fu\(k" => "$#%!",
				"fucker" => "[censored]",
				"fucking" => "[censored]",
				"fuckwit" => "[censored]",
				"fuk" => "[censored]",
				"fuking" => "[censored]",
				"futkretzn" => "[censored]",
				"fux0r" => "$#%!",
				"gook" => "[censored]",
				"h0r" => "[censored]",
				"handjob" => "[censored]",
				"helvete" => "[censored]",
				"honkey" => "[censored]",
				"hore" => "[censored]",
				"hump" => "[censored]",
				"injun" => "[censored]",
				"kawk" => "[censored]",
				"kike" => "[censored]",
				"knulle" => "[censored]",
				"kraut" => "[censored]",
				"kuk" => "[censored]",
				"kuksuger" => "[censored]",
				"kurac" => "[censored]",
				"kurwa" => "[censored]",
				"langer" => "[censored]",
				"masturbation" => "[censored]",
				"merd" => "[censored]",
				"motherfucker" => "[censored]",
				"motherfuckingcocksucker" => "[censored]",
				"mutherfucker" => "[censored]",
				"nepesaurio" => "[censored]",
				"nigga" => "[censored]",
				"nigger" => "[censored]",
				"nonce" => "[censored]",
				"nutsack" => "[censored]",
				"one\-eyed\-trouser\-snake" => "[censored]",
				"penis" => "[censored]",
				"picka" => "[censored]",
				"pissant" => "[censored]",
				"pizda" => "[censored]",
				"politician" => "[censored]",
				"prick" => "[censored]",
				"puckface" => "[censored]",
				"pule" => "[censored]",
				"pussy" => "[censored]",
				"puta" => "[censored]",
				"puto" => "[censored]",
				"rimjob" => "[censored]",
				"rubber" => "[censored]",
				"scheisse" => "[censored]",
				"schlampe" => "[censored]",
				"schlong" => "[censored]",
				"screw" => "[censored]",
				"shit" => "****",
				"shite" => "*****",
				"shiteater" => "[censored]",
				"shiz" => "[censored]",
				"skribz" => "[censored]",
				"skurwysyn" => "[censored]",
				"slut" => "[censored]",
				"spermburper" => "[censored]",
				"spic" => "[censored]",
				"spierdalaj" => "[censored]",
				"splooge" => "[censored]",
				"spunk" => "[censored]",
				"tatas" => "[censored]",
				"tits" => "[censored]",
				"toss the salad" => "[censored]",
				"twat" => "[censored]",
				"unclefucker" => "[censored]",
				"vagina" => "[censored]",
				"vittu" => "[censored]",
				"votze" => "[censored]",
				"wank" => "[censored]",
				"wanka" => "[censored]",
				"wanker" => "[censored]",
				"wankers" => "[censored]",
				"wankstain" => "[censored]",
				"whore" => "[censored]",
				"wichser" => "[censored]",
				"wop" => "[censored]",
				"yed" => "[censored]",
	);

	foreach ($word as $bad => $good) {
	    $text = str_replace($bad, $good, $text);
    }
    return $text;
}
?>